[package]
name = "router-macro"

description = "router-macro"
edition     = { workspace = true }
license     = { workspace = true }
version     = { workspace = true }


[lints]
workspace = true


[dependencies]
router-core       = { workspace = true }
router-macro-impl = { workspace = true }
